### ISSUE TITLE
Benchpark Rewrite Roadmap 

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#332]
- [x] System init, docs.  #298 - merging 8/19
- [x] Experiment init, docs.  #331 @alecbcs @becker33  - merge before 8/22
- [x] Re-create all existing LC systems (manual checking) @august-knox - start 8/22 
- [x] Re-create all existing experiments (manual checking) @august-knox - start 8/22

(feature parity here)

- [x] Add dry run test for new experiments and new systems. #343 @alecbcs @scheibelp 
- [x] Enable Caliper modifiers with our new experiments. #352 @rfhaque 
- [x] Add equivalence test for experiments - doing this manually for now  #353 @becker33 #354 @scheibelp 
- [x] Make progress on spack diff  
- [x] Workflow docs (aspirational to start and keep us on track).  #333 @dyokelson @alecbcs 
- [ ] Unifying command to generate a workspace (tied with workflow docs) #336
        This is to support the next item
- [ ] Implement compatibility checking between system (provides cuda) and experiment (requires cuda).  Design 8/26
        Allows `Experiment`s to assume they have a compatible `System` for all initialization methods
        `System`s define `provides` and `Experiment`s define `requires`
        Compatibility information is consumed by concretizer for `ExperimentSpec` #724
- [x] Break cmds into their own files. (Spackify the lib/ structure.) @becker33 
- [x] System create, docs (with a template like `spack create foo`)
- [x] Experiment create, docs (with a template  `spack create foo`)
- [x] Mechanism to pass Benchpark and Ramble variables to Caliper #355 @dyokelson

**Comment by pearce8** [comment]
The remaining 2 items are addressed in #336 and #724.
