### ISSUE TITLE
Extend docs to specify checklist of what's needed for experiment

### ISSUE THREAD

**Issue by slabasan** [LLNL/benchpark#424]
How can each item be tested in GitHub CI, and at which stage:

- [ ] benchpark audit 
- [ ] ramble dryrun
- [ ] ramble setup
- [ ] ramble on - a test will run a problem on a single x86 node

**Mandatory**: 

- [ ] single node #492 
- [ ] CPU-only problem - an x86 test?  The allocation modifier makes sure there is an experiment with 0 GPUs required?
- [ ] 1 prog model (i.e., derived from ??) - can benchpark audit be used for this?
- [x] add a ``dryrun``
- [ ] exit code from main - can only be tested when the test is running (ramble on) - how does GitLab CI test this?

**Optional**: 

- [ ] caliper/adiak integration (i.e., derived from CaliperExperiment?) - can benchpark audit be used for this?
- [ ] GPU prog models (i.e., derived from CudaExperiment, RocmExperiment?) - can benchpark audit be used for this?
- [ ] FOM+problem size
